### Hiera data
apiVersion: v1
kind: PersistentVolume
metadata:
  name: puppet-hiera-pv
  labels:
    {{- include "puppetserver.hiera.labels" . | nindent 4 }}
    {{- if .Values.storage.label }}
    type: {{ .Values.storage.label }}
    {{- end }}
spec:
  capacity:
    storage: {{ .Values.storage.size | quote }}
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
{{- if .Values.storage.nodeAffinity }}
  nodeAffinity:
{{ toYaml .Values.storage.nodeAffinity | nindent 4 }}
{{- end }}
{{- if .Values.storage.type }}
{{ toYaml .Values.storage.type | nindent 2 }}
{{- end }}
...
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: puppet-hiera-claim
  labels:
    {{- include "puppetserver.hiera.labels" . | nindent 4 }}
    {{- if .Values.storage.label }}
    type: {{ .Values.storage.label }}
    {{- end }}
{{- if .Values.storage.annotations }}
  annotations:
{{ toYaml .Values.storage.annotations | nindent 4 }}
{{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size | quote }}
{{- if .Values.storage.storageClass }}
{{- if (eq "-" .Values.storage.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.storage.storageClass }}"
{{- end }}
{{- end }}
...
