### Postgres data
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    {{- include "puppetserver.postgres.labels" . | nindent 4 }}
    {{- if .Values.storage.type }}
    type: {{ .Values.storage.type }}
    {{- end }}
spec:
  capacity:
    storage: {{ .Values.storage.size | quote }}
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
{{- if .Values.storage.nodeAffinity }}
  nodeAffinity:
{{ toYaml .Values.storage.nodeAffinity | nindent 4 }}
{{- end }}
...
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-claim
  labels:
    {{- include "puppetserver.postgres.labels" . | nindent 4 }}
    {{- if .Values.storage.type }}
    type: {{ .Values.storage.type }}
    {{- end }}
{{- if .Values.storage.annotations }}
  annotations:
{{ toYaml .Values.storage.annotations | nindent 4 }}
{{- end }}
spec:
  selector:
    matchLabels:
      {{- include "puppetserver.postgres.matchLabels" . | nindent 6 }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size | quote }}
{{- if .Values.storage.storageClass }}
{{- if (eq "-" .Values.storage.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.storage.storageClass }}"
{{- end }}
{{- end }}
...
