apiVersion: v1
kind: Service
metadata:
  name: {{ template "puppetserver.puppetserver.serviceName" . }}
  labels:
    {{- include "puppetserver.puppetserver.labels" . | nindent 4 }}
  {{- if .Values.puppetserver.service.labels }}
    {{ toYaml .Values.puppetserver.service.labels | nindent 4 }}
  {{- end }}
{{- if .Values.puppetserver.service.annotations }}
  annotations:
    {{ toYaml .Values.puppetserver.service.annotations | nindent 4 }}
{{- end }}
spec:
  ports:
  {{- range $key, $value := .Values.puppetserver.service.ports }}
    - name: {{ $key }}
{{ toYaml $value | indent 6 }}
  {{- end }}
  selector:
    {{- include "puppetserver.puppetserver.matchLabels" . | nindent 4 }}
  type: {{ .Values.puppetserver.service.type }}
{{- if (and (eq .Values.puppetserver.service.type "LoadBalancer") (not (empty .Values.puppetserver.service.loadBalancerIP))) }}
  loadBalancerIP: {{ .Values.puppetserver.service.loadBalancerIP }}
{{- end }}
