### Puppetserver data
{{- if (.Values.storage.staticPersistentVolumes.enabled) }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: puppet-puppet-pv
  labels:
    {{- include "puppetserver.puppetserver.labels" . | nindent 4 }}
    {{- if (.Values.storage.staticPersistentVolumes.typeLabel) }}
    type: {{ .Values.storage.staticPersistentVolumes.typeLabel }}
    {{- end }}
  {{- if .Values.storage.extraLabels }}
{{ toYaml .Values.storage.extraLabels | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
spec:
  capacity:
    storage: {{ .Values.storage.size | quote }}
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: puppet-puppet-claim
    namespace: {{ .Release.Namespace }}
{{- if .Values.storage.storageClass }}
{{- if (eq "-" .Values.storage.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.storage.storageClass }}"
{{- end }}
{{- end }}
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
{{- if .Values.storage.staticPersistentVolumes.nodeAffinity }}
  nodeAffinity:
{{ toYaml .Values.storage.staticPersistentVolumes.nodeAffinity | nindent 4 }}
{{- end }}
{{- if .Values.storage.staticPersistentVolumes.type }}
{{ toYaml .Values.storage.staticPersistentVolumes.type | nindent 2 }}
{{- end }}
{{- end }}
...
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: puppet-puppet-claim
  labels:
    {{- include "puppetserver.puppetserver.labels" . | nindent 4 }}
    {{- if and (.Values.storage.staticPersistentVolumes.enabled) (.Values.storage.staticPersistentVolumes.typeLabel) }}
    type: {{ .Values.storage.staticPersistentVolumes.typeLabel }}
    {{- end }}
{{- if .Values.storage.annotations }}
  annotations:
{{ toYaml .Values.storage.annotations | nindent 4 }}
{{- end }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.storage.selector }}
  selector:
    matchLabels:
      {{- include "puppetserver.puppetserver.matchLabels" . | nindent 6 }}
  {{- end }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.size | quote }}
{{- if .Values.storage.storageClass }}
{{- if (eq "-" .Values.storage.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.storage.storageClass }}"
{{- end }}
{{- end }}
...
