{{- if .Values.puppetserver.preGeneratedCertsJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "puppetserver.fullname" . }}-preinstall
  labels:
    {{- include "puppetserver.puppetserver.labels" . | nindent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "100"
spec:
  activeDeadlineSeconds: "{{.Values.puppetserver.preGeneratedCertsJob.jobDeadline}}"
  template:
    metadata:
      name: {{ template "puppetserver.fullname" . }}-preinstall
      labels:
        {{- include "puppetserver.puppetserver.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: copy-ro-puppetserver-certs
          image: "{{.Values.puppetserver.image}}:{{.Values.puppetserver.tag}}"
          imagePullPolicy: "{{.Values.puppetserver.pullPolicy}}"
          command: [ "sh", "-c" ]
          args:
            - mkdir -p /etc/puppetlabs/puppet/ssl;
              cp -a /puppetserver-certs/* /etc/puppetlabs/puppet/ssl;
          volumeMounts:
            - name: puppetserver-certs
              mountPath: /puppetserver-certs
            - name: puppet-puppet-storage
              mountPath: /etc/puppetlabs/puppet/
      volumes:
        - name: puppet-puppet-storage
          persistentVolumeClaim:
            claimName: puppet-puppet-claim
        - name: puppetserver-certs
          configMap:
            name: {{ template "puppetserver.fullname" . }}-preinstall
{{- end }}
