### Puppetserver data
apiVersion: v1
kind: PersistentVolume
metadata:
  name: puppet-serverdata-pv
  labels:
    {{- include "puppetserver.puppetserver.labels" . | nindent 4 }}
    {{- if .Values.storage.typeLabel }}
    type: {{ .Values.storage.typeLabel }}
    {{- end }}
  {{- if .Values.storage.extraLabels }}
{{ toYaml .Values.storage.extraLabels | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
spec:
  capacity:
    storage: {{ .Values.storage.size | quote }}
  claimRef:
    name: puppet-serverdata-claim
    namespace: {{ .Release.Namespace }}
{{- if .Values.storage.storageClass }}
{{- if (eq "-" .Values.storage.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.storage.storageClass }}"
{{- end }}
{{- end }}
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
{{- if .Values.storage.nodeAffinity }}
  nodeAffinity:
{{ toYaml .Values.storage.nodeAffinity | nindent 4 }}
{{- end }}
{{- if .Values.storage.type }}
{{ toYaml .Values.storage.type | nindent 2 }}
{{- end }}
...
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: puppet-serverdata-claim
  labels:
    {{- include "puppetserver.puppetserver.labels" . | nindent 4 }}
    {{- if .Values.storage.typeLabel }}
    type: {{ .Values.storage.typeLabel }}
    {{- end }}
{{- if .Values.storage.annotations }}
  annotations:
{{ toYaml .Values.storage.annotations | nindent 4 }}
{{- end }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.storage.selector }}
  selector:
    matchLabels:
      {{- include "puppetserver.puppetserver.matchLabels" . | nindent 6 }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size | quote }}
{{- if .Values.storage.storageClass }}
{{- if (eq "-" .Values.storage.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.storage.storageClass }}"
{{- end }}
{{- end }}
...
