### PuppetDB data
apiVersion: v1
kind: PersistentVolume
metadata:
  name: puppetdb-claim-pv
  labels:
    {{- include "puppetserver.puppetdb.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.storage.size | quote }}
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
...
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: puppetdb-claim
  labels:
    {{- include "puppetserver.puppetdb.labels" . | nindent 4 }}
{{- if .Values.storage.annotations }}
  annotations:
{{ toYaml .Values.storage.annotations | nindent 4 }}
{{- end }}
spec:
  selector:
    matchLabels:
      {{- include "puppetserver.puppetdb.matchLabels" . | nindent 6 }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size | quote }}
{{- if .Values.storage.storageClass }}
{{- if (eq "-" .Values.storage.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.storage.storageClass }}"
{{- end }}
{{- end }}
...
