{{- if and (.Values.puppetserver.puppeturl) (.Values.r10k.generate_types) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: r10k-generate-types-script
  labels:
    {{- include "puppetserver.r10k.labels" . | nindent 4 }}
data:
  generate-puppet-types.sh: |
    #!/usr/bin/env sh
    for environment in $1; do
      /opt/puppetlabs/bin/puppet generate types --environment $environment
    done
{{- end }}
